name: publish
on: [push]
jobs:
  publish-uptime-kumatb-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the uptime-kuma-TB Docker image
        run: |
          docker build ./docker --tag ghcr.io/tbruinsma/uptime-kuma:latest
          docker run ghcr.io/tbruinsma/uptime-kuma:latest
          docker push ghcr.io/tbruinsma/uptime-kuma:latest
